---
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'vendor/**/*'

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

RSpec/MultipleExpectations:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - let!
    - let
    - subject

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
