services:
  server:
    build:
      context: .
    ports:
      - '3000:3000'
    command: './bin/server'
    entrypoint: './entrypoint-server.sh'
    volumes:
      - .:/server
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      REDIS_URL: 'redis://redis:6379/1'
      WEBPACKER_DEV_SERVER_HOST: webpack
    depends_on:
      - webpack
      - redis
      - postgres

  webpack:
    build:
      context: .
    command: ./bin/webpack-dev-server
    entrypoint: './entrypoint-webpack.sh'
    volumes:
      - .:/server
    ports:
      - '3035:3035'
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  simulator:
    build:
      context: .
    command: rake data_points:simulate
    volumes:
      - .:/server
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      REDIS_URL: 'redis://redis:6379/1'
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    hostname: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379

  postgres:
    image: postgres
    hostname: postgres
    logging:
      driver: none
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432
